title: 'juedisch.info'
default_lang: 'de'
author:
  name: sb
  email: 'dev@juedisch.info'
metadata:
    description: 'Vernetzungsangebote für junge Jüdinnen und Juden.'
footer:
  social:
    title: Newsletter
    byline:
      # (values) bold | italic | uppercase | normal-case | small
      class: 'normal-case'
      text: Drei mal im Jahr Nachrichten und Berichte aus den Netzwerken per <span class="nowrap">E-Mail</span>.
    button:
      # (values) bold | italic | uppercase | normal-case | small | normal
      class: 'normal icon fa-envelope-o'
      text: 'Jetzt anmelden'
      url: 'https://newsletter.juedisch.info'
    # items:
      # -
        # title: YouTube
        # icon: fa fa-youtube-play
        # url: '#'
      # -
        # title: Facebook
        # icon: fa fa-facebook
        # url: '#'
      # -
        # title: Tickets
        # icon: fa fa-ticket
        # icon: fa fa-tags
        # url: '#'
  legal:
    credits:
      title: 'Freie Inhalte'
      id: '#frei'
    privacy:
      title: 'Datenschutz'
      id: '#datenschutz'
    notice:
      title: 'Impressum'
    #  id: ''
# do not remove taxonomy tag (identifier required in templates/partials/footer.html.twig)
taxonomies: [tag]
