title: 'juedisch.info'
default_lang: 'de'
author:
  name: sb
  email: 'dev@juedisch.info'
metadata:
    description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
footer:
  social:
    title: Connect with us
    byline: In posuere eleifend odio quisque semper.
    items:
      -
        title: YouTube
        icon: fa fa-youtube-play
        url: '#'
      -
        title: Facebook
        icon: fa fa-facebook
        url: '#'
      -
        title: Tickets
        # icon: fa fa-ticket
        icon: fa fa-tags
        url: '#'
  legal:
    credits:
      title: 'Förderung'
      id: '#foerderung'
    privacy:
      title: 'Datenschutz'
      id: '#datenschutz'
    notice:
      title: 'Impressum'
    #  id: ''
# do not remove taxonomy tag (identifier required in templates/partials/footer.html.twig)
taxonomies: [tag]
