title: 'juedisch.info'
# html lang only
default_lang: 'de'
author:
  name: sb
  email: 'dev@juedisch.info'
metadata:
  description: 'Vernetzungsangebote für junge Jüdinnen und Juden.'
# do not remove taxonomy tag (identifier required in templates/partials/footer.html.twig)
taxonomies: [tag]
